# Generated by Django 6.0.3 on 2026-03-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='user',
        ),
    ]
