# Generated by Django 6.0.3 on 2026-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_operation_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
