# Generated by Django 6.0.3 on 2026-03-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_last_operation_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskregistry',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
