"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = BASE_DIR / "src"

# Добавляем папку src в sys.path
sys.path.insert(0, str(SRC_DIR))

# Инициализация environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Чтение файла .env из корня проекта
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',

    'shop',
    'chat',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [SRC_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ==========================================
# Настройки Redis & Celery
# ==========================================

CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
# Маршрутизация задач по очередям
CELERY_TASK_ROUTES = {
    # Все задачи покупки/продажи отправляем в первую очередь
    'shop.tasks.trade_*': {'queue': 'trading_queue'},
}


# ==========================================
# Настройки Django Channels (WebSockets)
# ==========================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(env('REDIS_HOST'), env.int('REDIS_PORT'))],
        },
    },
}

from celery.schedules import crontab

# ==========================================
# Celery Beat Schedule (Периодические задачи)
# ==========================================
CELERY_BEAT_SCHEDULE = {
    # Яблоки
    "buy-apples": {"task": "shop.tasks.trade_buy_apples",
                   "schedule": crontab(minute="*/1")},
    "sell-apples": {"task": "shop.tasks.trade_sell_apples",
                    "schedule": crontab(minute="*/2")},

    # Ананасы
    "buy-pineapples": {"task": "shop.tasks.trade_buy_pineapples",
                       "schedule": crontab(minute="*/2")},
    "sell-pineapples": {"task": "shop.tasks.trade_sell_pineapples",
                        "schedule": crontab(minute="*/3")},

    # Бананы
    "buy-bananas": {"task": "shop.tasks.trade_buy_bananas",
                    "schedule": crontab(minute="*/3")},
    "sell-bananas": {"task": "shop.tasks.trade_sell_bananas",
                     "schedule": crontab(minute="*/4")},

    # Апельсины
    "buy-oranges": {"task": "shop.tasks.trade_buy_oranges",
                    "schedule": crontab(minute="*/4")},
    "sell-oranges": {"task": "shop.tasks.trade_sell_oranges",
                     "schedule": crontab(minute="*/5")},

    # Абрикосы
    "buy-apricots": {"task": "shop.tasks.trade_buy_apricots",
                     "schedule": crontab(minute="*/2")},
    "sell-apricots": {"task": "shop.tasks.trade_sell_apricots",
                      "schedule": crontab(minute="*/3")},

    # Киви
    "buy-kiwi": {"task": "shop.tasks.trade_buy_kiwi",
                 "schedule": crontab(minute="*/3")},
    "sell-kiwi": {"task": "shop.tasks.trade_sell_kiwi",
                  "schedule": crontab(minute="*/4")},

    # Персики
    "buy-peaches": {"task": "shop.tasks.trade_buy_peaches",
                    "schedule": crontab(minute="*/4")},
    "sell-peaches": {"task": "shop.tasks.trade_sell_peaches",
                     "schedule": crontab(minute="*/5")},
}
